from . import account_move
from . import account_move_line
from . import contacts
from . import invoice_report
from . import new_models
from . import pricelist
from . import product_template
from . import res_currency
from . import sale_order
from . import sale_order_line
from . import stock_picking
from . import transient_models
from . import account_payment
from . import description
from . import vendors
